/**
 * Bundled "A Minor Workout" practice schedule JSON.
 * Quarantined here so nothing outside ts/schedule/ needs to hold schedule data.
 */
export const A_MINOR_WORKOUT_SCHEDULE_JSON: string = JSON.stringify(
  {
    name: "A Minor Workout",
    items: [
      { rowType: "group", level: 1, name: "Warmup", color: "--note-second" },
      {
        rowType: "interval",
        duration: "3:00",
        task: "Fretboard survey — no labels, find the notes by ear",
        categoryName: "Instrument",
        featureTypeName: "Notes",
        featureArgsList: ["None"],
        intervalSettings: {},
      },
      { rowType: "group", level: 1, name: "Scales", color: "--note-fifth" },
      {
        rowType: "interval",
        duration: "4:00",
        task: "Natural minor — all positions, ascending & descending",
        categoryName: "Instrument",
        featureTypeName: "Scale",
        featureArgsList: ["Minor", "A"],
        intervalSettings: {},
      },
      {
        rowType: "interval",
        duration: "4:00",
        task: "Minor pentatonic — all five positions",
        categoryName: "Instrument",
        featureTypeName: "Scale",
        featureArgsList: ["Minor Pentatonic", "A"],
        intervalSettings: {},
      },
      {
        rowType: "interval",
        duration: "3:00",
        task: "Minor blues — add the blue note to the pentatonic",
        categoryName: "Instrument",
        featureTypeName: "Scale",
        featureArgsList: ["Minor Blues", "A"],
        intervalSettings: {},
      },
      {
        rowType: "interval",
        duration: "3:00",
        task: "Harmonic minor — raised 7th gives the classical sound",
        categoryName: "Instrument",
        featureTypeName: "Scale",
        featureArgsList: ["Harmonic Minor", "A"],
        intervalSettings: {},
      },
      { rowType: "group", level: 1, name: "Triads", color: "--note-seventh" },
      {
        rowType: "interval",
        duration: "5:00",
        task: "Minor triad shapes — root, 1st and 2nd inversion",
        categoryName: "Instrument",
        featureTypeName: "Triad Shapes",
        featureArgsList: ["A", "Minor"],
        intervalSettings: {},
      },
      {
        rowType: "interval",
        duration: "5:00",
        task: "Relative major triads (C Major) — same notes, different root",
        categoryName: "Instrument",
        featureTypeName: "Triad Shapes",
        featureArgsList: ["C", "Major"],
        intervalSettings: {},
      },
      {
        rowType: "interval",
        duration: "4:00",
        task: "Diminished triads (B°) — the tension chord of A minor",
        categoryName: "Instrument",
        featureTypeName: "Triad Shapes",
        featureArgsList: ["B", "Diminished"],
        intervalSettings: {},
      },
    ],
  },
  null,
  2,
);
